apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "grafana.fullname" . }}-image-renderer-egress
  namespace: {{ template "grafana.namespace" . }}
  annotations:
    comment: Limit image-renderer egress traffic to grafana
spec:
  podSelector:
    matchLabels:
      {{- include "grafana.imageRenderer.selectorLabels" . | nindent 6 }}
      {{- if .Values.imageRenderer.podLabels }}
        {{ toYaml .Values.imageRenderer.podLabels | nindent 6 }}
      {{- end }}

  policyTypes:
    - Egress

{{ end }}