apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mychart.fullname" . }}-image-renderer-egress
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  podSelector: {}
    

  policyTypes:
    - Egress

